version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - NODE_ENV=development

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  vite:
    build: .
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
